name: roofseg
channels:
  - conda-forge
dependencies:
  - albumentations
  - kornia
  - matplotlib
  - numpy
  - python=3.12.3
  - pytorch
  - segmentation-models-pytorch
  - pip:
    - ipykernel==6.27.1
    - wheel==0.43.0
