from typing import Protocol


class MetricTracker[T](Protocol):
    def log_metrics(self, metrics: T) -> None: ...


class MetricRestorer[T](Protocol):
    def restore_last_metrics(self) -> T | None: ...


class ArtifactTracker[T](Protocol):
    def save_model(self, model_state: T) -> None: ...
    def save_optimizer(self, optimizer_state) -> None: ...


class ArtifactRestorer[T](Protocol):
    def restore_model(self) -> T | None: ...
    def restore_optimizer(self) -> T | None: ...
