from typing import Protocol
from pathlib import Path

from roofseg.common.typing import Dataclass


class Tracker(Protocol):
    @property
    def artifacts_path(self) -> Path: ...
    def save_config(self, config: Dataclass) -> None: ...
    def log_metrics(self, metrics: Dataclass) -> None: ...
    def close(self) -> None: ...
