from typing import Protocol, Any
from pathlib import Path

class Tracker(Protocol):
    @property
    def artifacts_path(self) -> Path: ...
    def save_config(self, config: dict) -> None: ...
    def log_metrics(self, metrics: dict[str, Any]) -> None: ...
    def close(self) -> None: ...